#!/usr/bin/env bash
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
mkdir -p "$XDG_CONFIG_HOME/cvechecker"
mkdir -p "$XDG_DATA_HOME/cvechecker/local"
mkdir -p "$XDG_CACHE_HOME/cvechecker"
cat > "$XDG_CONFIG_HOME/cvechecker/cvechecker.conf" << EOF
dbtype = "sqlite";
cvecache = "$XDG_CACHE_HOME/cvechecker";
datadir = "/usr/share/cvechecker";
stringcmd = "/usr/bin/strings -n 3 '@file@'";
version_url = "https://raw.github.com/sjvermeu/cvechecker/master/versions.dat";
sqlite3: {
  localdb = "$XDG_DATA_HOME/cvechecker/local";
  globaldb = "$XDG_DATA_HOME/cvechecker/global.db";
};
EOF
